/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({ 'customer' : IDL.Null, 'farmer' : IDL.Null }),
  'contactInfo' : IDL.Opt(IDL.Text),
  'farmLocation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'farmerId' : IDL.Principal,
  'orderStatus' : OrderStatus,
  'orderDate' : IDL.Int,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Principal,
  'totalPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'farmerId' : IDL.Principal,
  'harvestLocation' : IDL.Text,
  'name' : IDL.Text,
  'pricePerUnit' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'harvestDate' : IDL.Text,
});
export const MarketplaceProduct = IDL.Record({
  'harvestLocation' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'pricePerUnit' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'harvestDate' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const FarmerProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'farmLocation' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Record({
          'harvestLocation' : IDL.Text,
          'name' : IDL.Text,
          'pricePerUnit' : IDL.Nat,
          'quantity' : IDL.Nat,
          'category' : IDL.Text,
          'harvestDate' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFarmerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getFarmerProducts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getMarketplaceProducts' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceProduct)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'registerFarmer' : IDL.Func([FarmerProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({ 'customer' : IDL.Null, 'farmer' : IDL.Null }),
    'contactInfo' : IDL.Opt(IDL.Text),
    'farmLocation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'farmerId' : IDL.Principal,
    'orderStatus' : OrderStatus,
    'orderDate' : IDL.Int,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Principal,
    'totalPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'farmerId' : IDL.Principal,
    'harvestLocation' : IDL.Text,
    'name' : IDL.Text,
    'pricePerUnit' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'harvestDate' : IDL.Text,
  });
  const MarketplaceProduct = IDL.Record({
    'harvestLocation' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'pricePerUnit' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'harvestDate' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const FarmerProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'farmLocation' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Record({
            'harvestLocation' : IDL.Text,
            'name' : IDL.Text,
            'pricePerUnit' : IDL.Nat,
            'quantity' : IDL.Nat,
            'category' : IDL.Text,
            'harvestDate' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFarmerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getFarmerProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getMarketplaceProducts' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceProduct)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'registerFarmer' : IDL.Func([FarmerProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };