/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FarmerProfile {
  'contactInfo' : string,
  'farmLocation' : string,
  'name' : string,
}
export interface MarketplaceProduct {
  'harvestLocation' : string,
  'productId' : bigint,
  'productName' : string,
  'pricePerUnit' : bigint,
  'quantity' : bigint,
  'category' : string,
  'harvestDate' : string,
  'farmerName' : string,
}
export interface Order {
  'id' : bigint,
  'farmerId' : Principal,
  'orderStatus' : OrderStatus,
  'orderDate' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
  'customerId' : Principal,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export interface Product {
  'id' : bigint,
  'farmerId' : Principal,
  'harvestLocation' : string,
  'name' : string,
  'pricePerUnit' : bigint,
  'quantity' : bigint,
  'category' : string,
  'harvestDate' : string,
}
export interface UserProfile {
  'userType' : { 'customer' : null } |
    { 'farmer' : null },
  'contactInfo' : [] | [string],
  'farmLocation' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      {
        'harvestLocation' : string,
        'name' : string,
        'pricePerUnit' : bigint,
        'quantity' : bigint,
        'category' : string,
        'harvestDate' : string,
      },
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFarmerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getFarmerProducts' : ActorMethod<[Principal], Array<Product>>,
  'getMarketplaceProducts' : ActorMethod<[], Array<MarketplaceProduct>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, bigint], undefined>,
  'registerFarmer' : ActorMethod<[FarmerProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];